name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install PocketIC server
      uses: dfinity/pocketic@main
    - name: Confirm successful installation
      run: "${POCKET_IC_BIN}" --version

