name: Unit Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install PocketIC server
      uses: dfinity/pocketic@main
      with:
        pocket-ic-server-version: '6.0.0'

    - name: Confirm successful installation
      run: ${{ env.POCKET_IC_BIN }} --version

